# Generated by Django 4.2.4 on 2023-12-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
