# Generated by Django 4.2.4 on 2023-12-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingredient_carbohydrates_ingredient_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
