# Generated by Django 4.2.4 on 2023-12-08 04:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_recipe_recipeingredient_recipes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
